[package]
name = "explorer"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "explorer"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.22.0"
thiserror = "1"
anyhow = "1"
mimalloc = { version = "*", default-features = false }
rand = { version = "0.8.4", features = ["alloc"] }
rand_pcg = "0.3.1"

[dependencies.polars]
git = "https://github.com/ritchie46/polars"
rev = "451ab7baea22955284eb407bb9c9281f79935ab3"
default-features = false
features = [
  "cross_join",
  "dtype-date32",
  "dtype-date64",
  "is_in",
  "json",
  "parquet",
  "pivot",
  "plain_fmt",
  "random",
  "rows",
  "simd",
  "sort_multiple",
  "strings",
  "temporal",
]
