name: Elixir CI
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  EXPLORER_BUILD: true
  RUST_TOOLCHAIN_VERSION: nightly-2023-06-23
  MIX_ENV: test

jobs:
  test:
    strategy:
      matrix:
        include:
          - otp_version: 25.3
            elixir_version: 1.14

          - otp_version: "26.0.2"
            elixir_version: 1.15

    runs-on: ubuntu-latest
    name: test
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            _build/test/lib/explorer/native/explorer
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: test-native-${{ runner.os }}-${{ env.RUST_TOOLCHAIN_VERSION }}-${{ hashFiles('native/**/Cargo.lock') }}
          restore-keys: |
            test-native-${{ runner.os }}-${{ env.RUST_TOOLCHAIN_VERSION }}

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "${{ env.RUST_TOOLCHAIN_VERSION }}"

      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp_version }}
          elixir-version: ${{ matrix.elixir_version }}

      - run: mix deps.get
      - run: mix deps.compile
      - name: Run tests
        run: mix test --warnings-as-errors
      - name: Compile once again but without optional deps
        run: mix compile --force --warnings-as-errors --no-optional-deps

      - name: Run cloud integration tests
        run: |
          mix localstack.setup
          mix test --only cloud_integration

  format:
    runs-on: ubuntu-latest
    name: mix format
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "26.0.2"
          elixir-version: 1.15
      - run: mix format --check-formatted
