name: Docs on GitHub pages

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}-docs
  cancel-in-progress: true

env:
  ELIXIR_VERSION: 1.14
  OTP_VERSION: 26.0
  EXPLORER_BUILD: true
  RUST_TOOLCHAIN_VERSION: nightly-2023-02-14

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # We have a different key for this cache because we run in a different mix env.
      - uses: actions/cache@v3
        with:
          path: |
            _build/dev/lib/explorer/native/explorer
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: dev-native-${{ runner.os }}-${{ env.RUST_TOOLCHAIN_VERSION }}-${{ hashFiles('native/**/Cargo.lock') }}
          restore-keys: |
            dev-native-${{ runner.os }}-${{ env.RUST_TOOLCHAIN_VERSION }}

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "${{ env.RUST_TOOLCHAIN_VERSION }}"

      - uses: erlef/setup-beam@v1
        with:
          otp-version: "${{ env.OTP_VERSION }}"
          elixir-version: "${{ env.ELIXIR_VERSION }}"

      - run: mix deps.get
      - run: mix docs
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: doc
