name: Rust CI
on:
  push:
    branches:
      - main
    paths:
      - "native/**"
  pull_request:
    paths:
      - "native/**"
  workflow_dispatch:

env:
  RUST_TOOLCHAIN_VERSION: nightly-2023-06-23

jobs:
  lint-rust:
    name: Lint Rust
    runs-on: ubuntu-latest
    strategy:
      matrix:
        manifest:
          - native/explorer/Cargo.toml

    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "${{ env.RUST_TOOLCHAIN_VERSION }}"
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v2
        with:
          env-vars: "RUST_TOOLCHAIN_VERSION"
          workspaces: |
            native/explorer

      - name: run rustfmt
        run: cargo fmt --manifest-path=${{ matrix.manifest }} --all -- --check

      - name: run clippy
        run: cargo clippy --manifest-path=${{ matrix.manifest }} -- -Dwarnings
